local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/images
public_folder: images
collections:
  - name: "about"
    label: "About Block"
    description: About and Board Positions
    files:
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Description", name: "body", widget: "markdown"}
        - { label: "TIC", name: "tic", widget: "string" }
        - label: 'Office Bearers'
          name: "board"
          widget: list
          fields:
            - { label: "Position", name: "position", widget: "string"}
            - { label: "Name", name: "name", widget: "string"}