local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: content/gallery
public_folder: /gallery

collections:
  - name: gallery
    label: Gallery
    description: Upload pictures to the Gallery
    files:
      - label: Pictures
        name: pics
        file: content/gallery.md
        fields:
        - label: 'Images'
          name: 'piclist'
          widget: list
          fields:
            - label: Image Source
              name: src
              widget: image
              media_folder: 'gallery'
              public_folder: ''
            - {label: Featured, name: featured, widget: boolean, default: false}
            - {label: Title, name: title, widget: string}
            - {label: Date, name: date, widget: datetime}
  - name: "home"
    label: "Home Page"
    description: About, Board Positions and Settings
    files:
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
      - { label: "Description", name: "body", widget: "markdown"}
      - { label: "Vision", name: "vision", widget: "text"}
      - { label: "Mission", name: "mission", widget: "text"}
      - { label: "TIC", name: "tic", widget: "string" }
      - label: 'Office Bearers'
        name: "board"
        widget: list
        fields:
          - { label: "Position", name: "position", widget: "string"}
          - { label: "Name", name: "name", widget: "string"}
    - label: 'Sign Up Form'
      name: 'signup'
      file: content/signup.md
      fields:
      - { label: 'Google Service Account Email', name: 'email', widget: 'string'}
      - { label: 'Private Key', name: 'key', widget: 'text'}
      - { label: 'Spreadsheet ID', name: 'id', widget: 'string'}
    - label: 'Social Links'
      name: 'social'
      file: content/social.md
      fields:
      - { label: 'Facebook', name: 'fb', widget: 'string'}
      - { label: 'YouTube', name: 'yt', widget: 'string'}
      - { label: 'Instagram', name: 'insta', widget: 'string'}